### PR TITLE
Fix module tab not updating bug

### LINKED ISSUE #77: Fix module tab not updating after command bug
After add, delete or edit command, the current version of AcademySource do not have it's module tab automatically update.

### PR DESCRIPTION
**Pull request by LonelyFort**
Fixes #77.

Now the modules tab will automatically update when there are changes inside the personList.

Additional feature implementation: removes filter on contact tab switch

### CODE REVIEW

File: src/main/java/seedu/address/ui/modulefolders/ModuleFolders.java [hunk 1]
```diff
@@ -35,35 +39,77 @@ public class ModuleFolders extends UiPart<Region> {
...
+
+            Set<String> moduleStringSet = new HashSet<>();
+
+            // Add all unique modules into a set
+            personList.forEach(person -> person.getModules()
+                    .stream()
+                    .sorted(Comparator.comparing(module -> module.toString()))
+                    .forEach(module -> moduleStringSet.add(module.getModuleCode())));
+
+            moduleStringSet.forEach(moduleString -> createFolder(moduleString, guiFunction));
```
Comment (wallacepck) [inline src/main/java/seedu/address/ui/modulefolders/ModuleFolders.java:79]: This could be a potential performance issue as it scales O(N), is it possible to cache this instead?

**Review by wallacepck — CHANGES_REQUESTED** [review]
LGTM, just a few nitpicks on abstraction and optimization

**Review by darrenchooji — COMMENTED** [review]
Overall, everything LGTM.

**Review by TeaMakesMePee — COMMENTED** [review]
looks good, just pass the checks!
