### PR TITLE
Fix UI codebase

### LINKED ISSUE #117: Fix codebase for UI to enhance encapsulation
Right now, codebase for UI violates a lot of Java rules and practices for convenience sake. Fix is required for this iteration to prepare for practical.

### PR DESCRIPTION
**Pull request by LonelyFort**
Fix principle violations occurring in Ui codebase and update UML diagram accordingly.

Fixes #117

### CODE REVIEW

File: src/main/java/seedu/address/ui/personlist/PersonListPanel.java [hunk 1]
```diff
@@ -36,6 +36,7 @@ public PersonListPanel(ObservableList<Person> personList) {
         personListView.setItems(personList);
         personListView.setCellFactory(listView -> new PersonListViewCell());
         personListView.setPlaceholder(createEmptyPlaceholder()); // Displays when personList is empty
+        personListView.setPlaceholder(createEmptyPlaceholder()); // Displays when personList is empty
     }
```
Comment (SAN-MUYUN) [inline src/main/java/seedu/address/ui/personlist/PersonListPanel.java:41]: LGTM

**Review by SAN-MUYUN — COMMENTED** [review]
LGTM
